name: mesh
description: Meshcoin cryptocurrency | Much coin, Such crypto
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies:
  cryptography: ^2.0.1
  hex: ^0.2.0
